# The URL the site will be built for
base_url = "https://k4ahr.work"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "anemone"
default_language = "en"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
generate_feeds = false



author = "K4ahr"

# Use name_en instead of name
header_nav = [
  { name_en = "/home/", url = "/" },
  { name_en = "/blog/", url = "/blog" },
  { name_en = "/link/", url = "/link" },
  { name_en = "/misc/", url = "/misc" },
  { name_en = "/about/", url = "/about" }
]